// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA6r_ZZWd0qLYj3SG9ZOl1yo-x5zPwyos',
    appId: '1:180632712016:web:7d36e19fe623e808ecb255',
    messagingSenderId: '180632712016',
    projectId: 'my-watchlist-app-c96d8',
    authDomain: 'my-watchlist-app-c96d8.firebaseapp.com',
    storageBucket: 'my-watchlist-app-c96d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkEGTKf1iATPA0z3IBIbgzNDkWf0KFOU',
    appId: '1:180632712016:android:45178374b58bc134ecb255',
    messagingSenderId: '180632712016',
    projectId: 'my-watchlist-app-c96d8',
    storageBucket: 'my-watchlist-app-c96d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bLmPgnA9s10m0obDCEx6c_uTnVCypE0',
    appId: '1:180632712016:ios:420a30d8883dc726ecb255',
    messagingSenderId: '180632712016',
    projectId: 'my-watchlist-app-c96d8',
    storageBucket: 'my-watchlist-app-c96d8.firebasestorage.app',
    iosBundleId: 'com.example.myWatchlistApp',
  );
}
